language: erlang
otp_release:
  - 23.0.4
  - 22.0
  - 21.3
  - 20.3
  - 19.3
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod u+x rebar3
  - ./rebar3 update
  - make
before_script:
  - epmd -daemon
script:
  - make verify-lampson-2pc
  - make verify-bernstein-ctp
  - make verify-skeen-3pc
  - ./rebar3 ct --suite=partisan_SUITE
notifications:
  email: christopher.meiklejohn@gmail.com
  slack: lasp-lang:hiPRNnbUa3zdGrrXZfGRAF7D
  irc: "irc.freenode.org#lasp-lang"
  webhooks:
      urls:
          - https://webhooks.gitter.im/e/1382c852fbaf2633033a
sudo: required
